### ISSUE TITLE
Shizoid is not working

### ISSUE THREAD

**Issue by bugworm** [top4ek/shizoid#13]
Лежит уже больше недели, в нескольких чатах не работает

**Comment by Bugagazavr** [comment]
Make shizoid great again

**Comment by tellmemoarlol** [comment]
Davai davai podnimaj snova

**Comment by top4ek** [comment]
Planning to rewrite completely this govnocode and after that only... may be :)

**Comment by top4ek** [comment]
Too heavy for all, sorry. You can run your own.

**Comment by Bugagazavr** [comment]
Well, if someone need you can use https://www.pepeground.org/
