### ISSUE TITLE
Shizoid repeats same stuff many times on almost all messeges

### ISSUE THREAD

**Issue by AnotherBugworm** [top4ek/shizoid#6]
In one chat he always repeat flac many times, like this:
Вот серьезно, сань flac flac flac flac flac.
On another chat - same stuff but another word:
Бля, ненавижу шг сверху kt kt kt kt kt?
Looks like this happens after posting words with dot on start, like:
.flac

**Comment by top4ek** [comment]
Possibly fixed in c59ff3d858d60e54099dc55e087f7ad7da22ac3f. Wiped DB, need more data to test.

**Comment by AnotherBugworm** [comment]
Looks like it fixed

**Comment by top4ek** [comment]
Yep :)
